## WE GATHER DATA IN DIFFERENT FORMATS
* CSV
* JSON/SQL
* FETCHING API
* WEB SCRAPING

# CSV--COMMA SEPERATED VALUES

## 1.IMPORTING PANDAS

In [1]:
import pandas as pd

## 2.OPENING A LOCAL CSV FILE

In [3]:
df=pd.read_csv("placement.csv")

## OPENING A CSV FILE FROM URL

In [6]:
import requests
from io import StringIO
url=""
header={"User Agent:"Mozilla/5.0(Macintosh;Intel Mac OS X 10.14;rv:66.0) Gecko/20100101 Firefox/66.0"
r=requests.get(url,headers=headers)
data=StringIO(req.text)
pdf.read_csv(data)

SyntaxError: unterminated string literal (detected at line 4) (2350100255.py, line 4)

## 4.sep parameter

* agar tsv format hai toh aise load karo data
* df=pf.read_csv("", sep='\t')
* by default agar kuch na dale toh sep=',' rehta hai

In [7]:
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.1   84.4          0
1            1   9.2  169.1          1
2            2   8.0  124.0          1
3            3   7.3  151.2          1
4            4   4.9  207.1          1
..         ...   ...    ...        ...
95          95   6.7  128.9          1
96          96   6.9  181.6          1
97          97   6.4  205.6          1
98          98   4.1  204.2          0
99          99   4.6  189.2          1

[100 rows x 4 columns]

In [8]:
df=pd.read_csv("placement.csv", names=['sno','marks','intelligence','job'])
df

            sno marks intelligence        job
0    Unnamed: 0  cgpa           iq  placement
1             0   6.1         84.4          0
2             1   9.2        169.1          1
3             2   8.0        124.0          1
4             3   7.3        151.2          1
..          ...   ...          ...        ...
96           95   6.7        128.9          1
97           96   6.9        181.6          1
98           97   6.4        205.6          1
99           98   4.1        204.2          0
100          99   4.6        189.2          1

[101 rows x 4 columns]

## 5. index_col parameter

### agar hamare paas data me koi aisa column hai jo use nhi aa rha toh use hum index me bhi change kar sakte hai 
* pd.read_csv("",index_col="jis column ko change karna hai uska naam")

## 2.header parameter

In [9]:
pd.read_csv("placement.csv", header=1) #ye hume batata hai ki row kahan se shuru karni hai

     0  6.1   84.4  0.1
0    1  9.2  169.1    1
1    2  8.0  124.0    1
2    3  7.3  151.2    1
3    4  4.9  207.1    1
4    5  4.9  114.9    0
..  ..  ...    ...  ...
94  95  6.7  128.9    1
95  96  6.9  181.6    1
96  97  6.4  205.6    1
97  98  4.1  204.2    0
98  99  4.6  189.2    1

[99 rows x 4 columns]

## 7.use_cols parameter

### pd.read_csv("placement.csv",usecols=[jo bhi colums chahiye daal do ]